
version: '2'

services:
  forwarder:
    image: forwarder-python:latest
    network_mode: "host"
    volumes:
      - ../config-files/forwarder_config_idle_updates_long.ini:/forwarder_config_idle_updates_long.ini
      - ../config-files/forwarder_config_idle_updates_long.json:/forwarder_config_idle_updates_long.json
      - ../logs/:/forwarder_logs/
    environment:
      CONFIG_FILE: "/forwarder_config_idle_updates_long.ini"
